HOST = "0.0.0.0"
PORT = 8765
VIDEO_STREAM_HOST = "0.0.0.0"
VIDEO_STREAM_PORT = 8766
VIDEO_STREAM_PATH = "/camera.mjpg"
AUDIO_STREAM_WS_PATH = "/audio.raw"
VIDEO_DEVICE_PATH = "/dev/video0"
VIDEO_FRAME_WIDTH = 1920
VIDEO_FRAME_HEIGHT = 1080
VIDEO_CAPTURE_FPS = 30
VIDEO_STREAM_FPS = 30
VIDEO_CAPTURE_BUFFER_SIZE = 1
VIDEO_RETRY_SECONDS = 1.0
VIDEO_RECORD_ENABLED = True
VIDEO_RECORD_FPS = 30
VIDEO_RECORD_WINDOW_SECONDS = 90 * 60
VIDEO_RECORD_CHUNK_SECONDS = 60

AUDIO_RECORD_ENABLED = True
AUDIO_RECORD_DEVICE = "plughw:2,0"
AUDIO_RECORD_SAMPLE_RATE = 48000
AUDIO_RECORD_CHANNELS = 1
AUDIO_RECORD_SAMPLE_FORMAT = "S16_LE"
AUDIO_RECORD_WINDOW_SECONDS = 90 * 60
AUDIO_RECORD_CHUNK_SECONDS = 60

SYSTEM_TIME_SYNC_ENABLED = True
SYSTEM_TIME_SYNC_MIN_DRIFT_MS = 10
SYSTEM_TIME_SYNC_COMMAND_TIMEOUT_SECONDS = 5.0

SENSOR_RECORD_WINDOW_SECONDS = 90 * 60

ADS1115_I2C_ADDRESS = 0x48
ADS1115_DATA_RATE = 860
ADS1115_GAIN = 2 / 3
PRESSURE_TRANSDUCER_CHANNELS = (0, 1, 2)
PRESSURE_TRANSDUCER_COUNT = len(PRESSURE_TRANSDUCER_CHANNELS)
PRESSURE_TRANSDUCER_MAX_PSI = 500.0
PRESSURE_TRANSDUCER_MAX_VOLTAGE = 5.0
PRESSURE_RAW_WINDOW_SECONDS = 30
PRESSURE_TRANSPORT_WINDOW_SECONDS = 10 * 60
PRESSURE_TRANSPORT_RATE_HZ = 60

LOAD_CELL_DATA_PIN = 6
LOAD_CELL_CLOCK_PIN = 5
LOAD_CELL_WINDOW_SECONDS = 10 * 60
LOAD_CELL_REFERENCE_UNIT = 1.0
LOAD_CELL_OFFSET = 0.0
LOAD_CELL_SAMPLES_PER_READING = 1

IGNITION_GPIO_PIN = 17

STATUS_LED_DATA_PIN = 24
STATUS_LED_PIXEL_COUNT = 1
STATUS_LED_IDLE_BLINK_INTERVAL_SECONDS = 0.5
STATUS_LED_ALERT_BLINK_INTERVAL_SECONDS = 0.1
STATUS_LED_IDLE_COLOR = (0, 255, 0)
STATUS_LED_ALERT_COLOR = (255, 128, 0)
STATUS_LED_ABORT_COLOR = (255, 0, 0)
STATUS_LED_ABORT_BLINK_INTERVAL_SECONDS = 0.1
STATUS_LED_ABORT_FLASH_SECONDS = 3.0

SERVO_CHANNELS = (0, 1, 2, 3, 4)
SERVO_TRANSITION_SECONDS = 0.4
SERVO_SLOW_OPEN_CHANNELS = (SERVO_CHANNELS[0], SERVO_CHANNELS[3])
SERVO_SLOW_OPEN_SECONDS = 15.0
SERVO_SLOW_OPEN_STEP_SECONDS = 0.05
SERVO_MEDIUM_SLOW_OPEN_CHANNELS = (SERVO_CHANNELS[1], SERVO_CHANNELS[2])
SERVO_MEDIUM_SLOW_OPEN_SECONDS = 2.7
SERVO_MEDIUM_SLOW_OPEN_STEP_SECONDS = 0.05
SERVO_SLOW_CLOSE_CHANNELS = SERVO_CHANNELS[1:4]
SERVO_SLOW_CLOSE_SECONDS = SERVO_SLOW_OPEN_SECONDS
SERVO_SLOW_CLOSE_STEP_SECONDS = SERVO_SLOW_OPEN_STEP_SECONDS

SERVO_CLOSED_ANGLE = 105.0
SERVO_OPEN_ANGLE = 10.0

PCA9685_I2C_ADDRESS = 0x40
PCA9685_PWM_FREQUENCY = 50
SERVO_MIN_PULSE_US = 500
SERVO_MAX_PULSE_US = 2500
SERVO_ACTUATION_RANGE = 180
